name: Activitarea Node

on: [push]

jobs:
  node-job:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Ver version de Node
        run: node -v

      - name: Ver version de npm
        run: npm -v

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar app
        run: node app.js